/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus.edu.levina;

import java.util.Set;
import java.util.TreeSet;

import com.google.common.collect.ImmutableSet;

public class App {
    public static void main(String... args) {
    	ImmutableSet<Person> persons = ImmutableSet.of(
    			new Person("name1", "sername1"),
    			new Person(null, "sername1"),
    			new Person("name3", "sername3"));
    	persons.forEach(System.out::println);
    }
}
